### DISCUSSION TITLE
Emails not getting triggered  for Custom Alert rules for Nginx

### DISCUSSION THREAD

**Discussion by sivaprakash123** [project-sunbird/sunbird-devops#3996] [General]
I have created Alert Rules for Nginx for a threshold limit on Nginx errors (4xx, 5xx). Below mentioned the alert rules for nginx. The alerts are not triggered though the expr is passed. Do i need to add/update labels or configuration in the prometheus-operator configuration for the nginx ? 

Please let me know if any other details required
```
groups:
- name: nginx-alert.rules
  rules:
  - alert: nginx_failure_alert_warning
    annotations:
      message: Nginx error (4xx / 5xx) error count is more than 500 for the last 10
        minutes
      summary: dev Nginx Error rate is above 500
    expr: sum(count_over_time(nginx_http_requests_total{status!~"2..|3.."}[10m]))
      by (status, count) > 500
    labels:
      severity: warning
```
